// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ggldxblzaoovzsrwmvla.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdnbGR4Ymx6YW9vdnpzcndtdmxhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYyMzc3NzQsImV4cCI6MjA3MTgxMzc3NH0.YKBaMd2o_F068YymDZOiFpBbJApqvI5YTtdMJCBbhUA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});